detectors:
  DuplicateMethodCall:
    max_calls: 2
  IrresponsibleModule:
    enabled: false
  TooManyStatements:
    max_statements: 10

directories:
  "app/controllers":
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/models":
    InstanceVariableAssumption:
      enabled: false
  "db/migrate":
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
    UncommunicativeVariableName:
      accept:
        - t
  "spec/support":
    UtilityFunction:
      enabled: false

