require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'spec/controllers/**/*'
    - 'spec/views/**/*'
#    - !ruby/regexp /old_and_unused\.rb$/
Rails:
  Enabled: true

Rails/BulkChangeTable:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'app/controllers/**/*'
    - 'spec/**/*'
    - 'db/migrate/**/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'db/seeds.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/factories.rb'
    - 'spec/models/**/*'
    - 'spec/requests/**/*'

RSpec/ExampleLength:
  Enabled: false
  Max: 8

RSpec/MultipleExpectations:
  Max: 3

RSpec/NestedGroups:
  Max: 8
