AllCops:
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'spec/controllers/**/*'
    - 'spec/views/**/*'
#    - !ruby/regexp /old_and_unused\.rb$/

Style/Documentation:
  Exclude:
    - 'app/controllers/**/*'
    - 'spec/**/*'
    - 'db/migrate/**/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'db/seeds.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/factories.rb'
    - 'spec/models/**/*'
    - 'spec/requests/**/*'
