AllCops:
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'test/**/*'
#    - !ruby/regexp /old_and_unused\.rb$/

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/LineLength:
  Max: 130
  Exclude:
    - 'db/seeds.rb'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%i':    '()'

Style/Documentation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false
