AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'db/seeds.rb'

Style/Documentation:
  Enabled: true